version: '3.8'

services:
  db:
    image: mariadb
    container_name: chatbot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tdah
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  chatbot:
    build: .
    container_name: chatbot-app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: tdah

volumes:
  db_data:
